---

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /cloud/owncloud/data
  - /cloud/owncloud/config
  - /cloud/owncloud/apps

- name: Copy default config
  template:
    src: autoconfig.php
    dest: /cloud/owncloud/config/autoconfig.php

- name: Add docker container
  docker:
    name: lc-owncloud
    image: "owncloud:{{ owncloud_version }}-apache"
    net: "{{ docker_network }}"
    state: reloaded
    volumes:
    - /cloud/owncloud/data:/var/www/html/data
    - /cloud/owncloud/config:/var/www/html/config
    - /cloud/owncloud/apps:/var/www/html/apps

- name: Add docker autostart
  docker_autostart:
    name: lc-owncloud
    state: present
