---

- name: Update the apt cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_timeout }}"

- name: Install common packages
  apt:
    name:
    - apt-transport-https
    - python-pip
    state: present
